# Generated by Django 4.1.7 on 2023-03-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_tags_options_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
